# Generated by Django 4.0.4 on 2022-05-20 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('apartment_Image', models.ImageField(blank=True, upload_to='apartment')),
                ('Location', models.CharField(max_length=300)),
                ('Apartment_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='app.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Paid', max_length=20)),
                ('Payment_Amount', models.IntegerField()),
                ('Currency_Code', models.CharField(max_length=6)),
                ('Apartment_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_name', to='app.property')),
                ('Room_Renter_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_name', to='app.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='Room_Renter',
            field=models.ManyToManyField(related_name='renter', to='app.tenant'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.DateField(default=django.utils.timezone.now)),
                ('Invoice', models.FileField(upload_to='invoice')),
                ('Category', models.CharField(default='', max_length=30)),
                ('Payment_Amount', models.IntegerField(default=False)),
                ('Status', models.CharField(choices=[('Approved', 'Approved'), ('Requested', 'Requested'), ('Declined', 'Declined')], default='Requested', max_length=20)),
                ('Apartment_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_apartment', to='app.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tenant')),
            ],
        ),
    ]
