# Generated by Django 4.0.4 on 2022-05-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Requested', 'Requested'), ('Declined', 'Declined')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Payment_Amount',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='Room_Renter',
            field=models.ManyToManyField(related_name='renter', to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Apartment_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_name', to='app.property'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Room_Renter_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_name', to='app.tenant'),
        ),
    ]
