# Generated by Django 3.2.10 on 2022-05-05 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('apartmentImage', models.ImageField(blank=True, upload_to='apartment')),
                ('ApartmentOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL)),
                ('RoomRenter', models.ManyToManyField(related_name='renter_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
