# Generated by Django 3.2.10 on 2022-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ApartmentOwner',
            new_name='Apartment_Owner',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='RoomRenter',
            new_name='Room_Renter',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='apartmentImage',
            new_name='apartment_Image',
        ),
    ]
