# Generated by Django 3.2.10 on 2022-05-05 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20220505_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Location',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Payment_Amount', models.IntegerField()),
                ('Currency_Code', models.CharField(max_length=6)),
                ('Apartment_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
                ('Room_Renter_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
