# Generated by Django 4.0.4 on 2022-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_expense_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Declined_Message',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
