# Generated by Django 3.2.10 on 2022-05-05 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220505_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Rent',
        ),
    ]
