# Generated by Django 4.0.4 on 2022-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expense_declined_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Currency_Code',
            field=models.CharField(default='EUR', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='Profile_Image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='property',
            name='Room_Rent_Amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='Profile_Image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='Title',
            field=models.CharField(default='Maintainance invoice', max_length=120),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
